version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/devQuiz
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:5
    container_name: devquiz-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
 mongo-data: